export const projectMap  = new Map([
    ['discord-rpg-game',
        {
            name: 'Discord RPG Game',
            descriptionShort: 'Using Discord, a free VoIP app, players can play and interact with each other in an MMORPG through text input.',
            stacks: 'Node.js, PostgreSQL',
            github: 'https://github.com/TerrenceJChan/discord-rpg-game',
        },
    ],
    ['next-portfolio',
        {
            name: 'Next Portfolio',
            descriptionShort: 'This site! Created using Next.js and Sass.',
            stacks: 'Next.js, Sass',
            github: 'https://github.com/TerrenceJChan/next-portfolio',
        },
    ],
    // UofT Projects
    ['project3',
        {
            name: 'Project 3: Mind Decks',
            descriptionShort: 'An interactive flash cards app built on a MERN stack.',
            stacks: 'Mongoose, Express.js, React, Node.js',
            github: 'https://github.com/Uot-Project3-Group05/uot-project3-group5',
        },
    ],
    ['react-portfolio',
        {
            name: 'Challenge 15: React Portfolio',
            descriptionShort: 'Personal portfolio (not this one) built with React. Features conditional rendering and subtle animations.',
            stacks: 'React',
            github: 'https://github.com/TerrenceJChan/react-portfolio',
        },
    ],
    ['budget-tracker',
        {
            name: 'Challenge 14: PWA Budget Tracker',
            descriptionShort: 'Tracks and graphs the user\'s spending habits. Can be installed and used as a PWA.',
            stacks: 'Node.js, Express.js, Mongoose',
            github: 'https://github.com/TerrenceJChan/budget-tracker',
        },
    ],
    ['social-network-api',
        {
            name: 'Challenge 13: Social Network API',
            descriptionShort: 'A Mongoose database that accepts CRUD operations for a rudimentary social network API.',
            stacks: 'Node.js, Express.js, Mongoose',
            github: 'https://github.com/TerrenceJChan/social-network-api',
        },
    ],
    ['project2',
        {
            name: 'Project 2: Dangles Fantasy Sports',
            descriptionShort: 'Fantasy sports site where users can pick their favourite hockey players to form a team and track their progress.',
            stacks: 'Node.js, MySQL, Sequelize, Heroku',
            github: 'https://github.com/uoft-project2-group7/project',
        },
    ],
    ['tech-blog',
        {
            name: 'Challenge 12: Tech Blog',
            descriptionShort: 'A content management system that allows the user to make, edit, and comment on blog posts.',
            stacks: 'Node.js, MySQL, Sequelize, Heroku',
            github: 'https://github.com/TerrenceJChan/tech-blog',
        },
    ],
    ['e-commerce-backend',
        {
            name: 'Challenge 11: E-Commerce Back End',
            descriptionShort: 'Access and edit the backend database of an e-commerce store.',
            stacks: 'Node.js, Express.js, MySQL',
            github: 'https://github.com/TerrenceJChan/e-commerce-backend',
        },
    ],
    ['employee-tracker',
        {
            name: 'Challenge 10: Employee Tracker',
            descriptionShort: 'Add and retrieve employee information from a MySQL database.',
            stacks: 'Node.js, MySQL',
            github: 'https://github.com/TerrenceJChan/employee-tracker',
        },
    ],
    ['note-taker',
        {
            name: 'Challenge 9: Note Taker',
            descriptionShort: 'Saves scratch notes onto a Heroku server to be looked at later.',
            stacks: 'Node.js, Express.js, Heroku',
            github: 'https://github.com/TerrenceJChan/note-taker',
        },
    ],
    ['team-profile-generator',
        {
            name: 'Challenge 8: Team Profile Generator',
            descriptionShort: 'Generates an HTML site listing the directory of a work team, based on user input.',
            stacks: 'Node.js',
            github: 'https://github.com/TerrenceJChan/team-profile-generator',
        },
    ],
    ['readme-generator',
        {
            name: 'Challenge 7: README Generator',
            descriptionShort: 'Generates a README.md file based on user input.',
            stacks: 'Node.js',
            github: 'https://github.com/TerrenceJChan/readme-generator',
        },
    ],
    ['cocktail-map',
        {
            name: 'Project 1: Interactive Front-End Project',
            descriptionShort: 'A mock business site that generates cocktail suggestions using an open API.',
            stacks: 'Foundation, TheCocktailDB API, Food Database API',
            github: 'https://github.com/uoft-project1-group5/cocktail-map',
        },
    ],
    ['weather-dashboard',
        {
            name: 'Challenge 6: Weather Dashboard',
            descriptionShort: 'Displays the weather forecast of any major city in the world.',
            stacks: 'Tailwind.css, openweathermap API',
            github: 'https://github.com/TerrenceJChan/weather-dashboard',
        },
    ],
    ['day-planner',
        {
            name: 'Challenge 5: Day Planner',
            descriptionShort: 'A day planner that saves notes and changes colours depending on the time of day.',
            stacks: 'JavaScript, Moment.js',
            github: 'https://github.com/TerrenceJChan/day-planner',
        },
    ],
    ['coding-quiz',
        {
            name: 'Challenge 4: Coding Quiz',
            descriptionShort: 'Saves users score on an online quiz to the browser\'s local Storage. Features JavaScript intervals.',
            stacks: 'JavaScript',
            github: 'https://github.com/TerrenceJChan/coding-quiz',
        },
    ],
    ['password-generator',
        {
            name: 'Challenge 3: Password Generator',
            descriptionShort: 'Generates a password using JavaScript Dialogue boxes with validation checks.',
            stacks: 'JavaScript',
            github: 'https://github.com/TerrenceJChan/password-generator/tree/prompt-method',
        },
    ],
    ['personal-portfolio',
        {
            name: 'Challenge 2: Personal Portfolio',
            descriptionShort: 'Making a simple portfolio page. Features autoscrolling and background video playing.',
            stacks: 'HTML, CSS',
            github: 'https://github.com/TerrenceJChan/personal-portfolio',
        },
    ],
    ['horiseon',
        {
            name: 'Challenge 1: Code Refactoring',
            descriptionShort: 'Refactoring a mock business page\'s HTML and CSS to not have redundant code.',
            stacks: 'HTML, CSS',
            github: 'https://github.com/TerrenceJChan/horiseon',
        },
    ],
]);
