import Head from 'next/head';
import Image from 'next/image';

import SectionMain from '../components/SectionMain';
import Footer from '../components/Footer';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <SectionMain />
            <Footer />
        </div>
    );
}
