import Head from 'next/head';

import SectionMain from '../components/SectionMain';
import SectionBio from '../components/SectionBio';
import SectionProjects from '../components/SectionProjects';
import Background from '../components/Background';
import Footer from '../components/Footer';

export default function Home() {
    return (
        <div>
            <Background />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <SectionMain />
                <SectionBio />
                <SectionProjects />
                <Footer />
            </main>
        </div>
    );
}
